"use client";

import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({session, children }) {
  return (
    <html lang="en">
      <body >
      <SessionProvider session={session}>
      {children}
      </SessionProvider>
      </body>
    </html>
  )
}
